# ============================================================
# NovexOS - Makefile
# ============================================================

# --- Toolchain ---
# Look for x86_64-elf-gcc, otherwise fall back to the system GCC
IS_CROSS := $(shell command -v x86_64-elf-gcc 2>/dev/null && echo yes || echo no)

ifeq ($(IS_CROSS),yes)
	CC       := x86_64-elf-gcc
	AS       := x86_64-elf-gcc   # route through gcc for the C preprocessor
	LD       := x86_64-elf-ld
	OBJCOPY  := x86_64-elf-objcopy
	CFLAGS   := -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Werror -Isrc \
	             -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2
	LDFLAGS  := -T linker.ld -melf_x86_64 -n
	ASFLAGS  := -x assembler-with-cpp -c -m64
else
	CC       := gcc
	AS       := gcc              # route through gcc for the C preprocessor
	LD       := ld
	OBJCOPY  := objcopy
	CFLAGS   := -std=gnu99 -ffreestanding -O2 -Wall -Wextra -Werror -Isrc \
	             -m64 -mcmodel=large -mno-red-zone -mno-mmx -mno-sse -mno-sse2
	LDFLAGS  := -T linker.ld -melf_x86_64 -n
	ASFLAGS  := -x assembler-with-cpp -c -m64
endif

# --- Source directories and files ---
SRCDIR  := src
OBJDIR  := build

# Kernel assembly files (routed through gcc for #define support)
ASM_SRC := $(SRCDIR)/boot.s $(SRCDIR)/interrupts.s
C_SRC   := $(wildcard $(SRCDIR)/*.c)

ASM_OBJ  := $(OBJDIR)/boot.o $(OBJDIR)/interrupts.o
C_OBJ    := $(patsubst $(SRCDIR)/%.c,$(OBJDIR)/%.o,$(C_SRC))
# loader_bin.o is generated by objcopy from the 16-bit loader binary
LOADER_OBJ := $(OBJDIR)/loader_bin.o
OBJECTS  := $(ASM_OBJ) $(C_OBJ) $(LOADER_OBJ)

# --- Output files ---
KERNEL   := novexos.bin
ISO      := novexos.iso
DISK_IMG := disk.img

# ============================================================
# PNG assets -> C headers (requires Python 3 + Pillow)
# Run 'make assets' after adding or modifying any PNG in src/assets/.
# The generated *_img.h files are committed to the repo so that a plain
# 'make' works even without Python/Pillow installed.
#
# Cursors    : 16x16   (src/assets/mouse_pointer/*.png)
# Background : 1024x768 (src/assets/background.png)
# ============================================================
ASSETS_SCRIPT := tools/png_to_header.py

# Cursor headers (16x16)
CURSOR_PNGS    := $(SRCDIR)/assets/mouse_pointer/pointer.png
CURSOR_HEADERS := $(SRCDIR)/assets/mouse_pointer/pointer_img.h

# Background header (1024x768)
BG_PNG    := $(SRCDIR)/assets/background.png
BG_HEADER := $(SRCDIR)/assets/background_img.h

ASSET_HEADERS := $(CURSOR_HEADERS) $(BG_HEADER)

assets: $(ASSET_HEADERS)
	@echo ""
	@echo "========================================="
	@echo " Assets regenerated ($(words $(ASSET_HEADERS)) headers)"
	@echo "========================================="

# Cursor sprites — 16x16
$(SRCDIR)/assets/mouse_pointer/%_img.h: $(SRCDIR)/assets/mouse_pointer/%.png $(ASSETS_SCRIPT)
	python3 $(ASSETS_SCRIPT) $< $@ 16 16

# Background — 1024x768 (matches default VBE resolution -> zero-cost blit)
$(BG_HEADER): $(BG_PNG) $(ASSETS_SCRIPT)
	python3 $(ASSETS_SCRIPT) $< $@ 1024 768

# assets.o depends on all generated headers
$(OBJDIR)/assets.o: $(ASSET_HEADERS)

# ============================================================
# Default target
# ============================================================
all: $(KERNEL)
	@echo ""
	@echo "========================================="
	@echo " NovexOS compiled : $(KERNEL)"
	@echo " Launch with : make run"
	@echo "========================================="

# ============================================================
# Main kernel linking
# ============================================================
$(KERNEL): $(OBJECTS)
	$(LD) $(LDFLAGS) -o $@ $^

# ============================================================
# Assemble kernel .s files (via gcc for #define support)
# ============================================================
$(OBJDIR)/boot.o: $(SRCDIR)/boot.s | $(OBJDIR)/.created
	$(AS) $(ASFLAGS) $< -o $@

$(OBJDIR)/interrupts.o: $(SRCDIR)/interrupts.s | $(OBJDIR)/.created
	$(AS) $(ASFLAGS) $< -o $@

# ============================================================
# Compile .c files
# ============================================================
$(OBJDIR)/%.o: $(SRCDIR)/%.c | $(OBJDIR)/.created
	$(CC) -c $< -o $@ $(CFLAGS)

# ============================================================
# Build the 16-bit loader (real mode -> flat binary)
#
# 1. Assemble loader.s into ELF with as (16-bit, no CPP)
# 2. Link into a flat binary starting at 0x0
# 3. Convert the .bin into .o (symbols _binary_..._start/end/size)
# ============================================================
$(OBJDIR)/loader.o: $(SRCDIR)/loader.s | $(OBJDIR)/.created
	as --32 $< -o $@

$(OBJDIR)/loader.elf: $(OBJDIR)/loader.o
	ld -m elf_i386 -Ttext=0x0 $< -o $@

$(OBJDIR)/loader.bin: $(OBJDIR)/loader.elf
	$(OBJCOPY) -O binary $< $@

# objcopy embed: generates the symbols referenced by shell.c:
#   _binary_build_loader_bin_start
#   _binary_build_loader_bin_end
#   _binary_build_loader_bin_size
$(OBJDIR)/loader_bin.o: $(OBJDIR)/loader.bin
	$(OBJCOPY) \
		-I binary \
		-O elf64-x86-64 \
		-B i386:x86-64 \
		--rename-section .data=.rodata,alloc,load,readonly,data,contents \
		$< $@

# ============================================================
# Create the build directory (sentinel to avoid name conflict
# with the phony target "build")
# ============================================================
$(OBJDIR)/.created:
	mkdir -p $(OBJDIR)
	@touch $@

# ============================================================
# Create empty disk image (200 MB)
# ============================================================
$(DISK_IMG):
	dd if=/dev/zero of=$@ bs=1M count=200

# ============================================================
# make run — Compile, generate ISO and launch QEMU
# The ISO is a hybrid MBR (flashable to USB with dd)
# ============================================================
run: assets $(ISO) $(DISK_IMG)
	@echo ""
	@echo ">>> Launching NovexOS in QEMU..."
	@echo ">>> (Quit: close the window or Ctrl+C in the terminal)"
	@echo ""
	qemu-system-x86_64 \
		-drive file=$(ISO),format=raw,index=1,media=cdrom \
		-drive file=$(DISK_IMG),format=raw,index=0,media=disk \
		-boot d \
		-m 512M \
		-device VGA,vgamem_mb=16 \
		-serial stdio \
		-name "NovexOS"

# ============================================================
# Create bootable ISO (requires grub-mkrescue + xorriso)
# grub-mkrescue generates a hybrid MBR ISO -> flashable to USB
# ============================================================
$(ISO): $(KERNEL)
	@mkdir -p isodir/boot/grub
	@cp $(KERNEL) isodir/boot/novexos.bin
	@printf 'set timeout=3\nset default=0\n\nmenuentry "NovexOS" {\n    multiboot /boot/novexos.bin\n    boot\n}\n' \
		> isodir/boot/grub/grub.cfg
	grub-mkrescue -o $(ISO) isodir 2>/dev/null
	@rm -rf isodir
	@echo ""
	@echo "========================================="
	@echo " ISO created : $(ISO)"
	@echo " Flash to USB:"
	@echo "   sudo dd if=$(ISO) of=/dev/sdX bs=4M status=progress"
	@echo "========================================="

# ============================================================
# make build — Compile the kernel and generate the ISO
# First regenerates PNG assets if needed.
# ============================================================
build: assets $(ISO)
	@echo ""
	@echo "========================================="
	@echo " Build complete : $(ISO)"
	@echo " Launch with   : make run"
	@echo "========================================="

# ============================================================
# make clean — Delete all generated files
# ============================================================
clean:
	@rm -rf $(OBJDIR) $(KERNEL) $(ISO) $(DISK_IMG) isodir
	@echo "Clean complete."

.PHONY: all build clean run assets
