#!/usr/bin/env python3
"""
NovexOS - PNG to C header converter
Converts a PNG image into a C header containing a uint32_t ARGB pixel array.

Usage:
    python3 tools/png_to_header.py <input.png> <output.h> [width height]

Defaults: 32x32 pixels.
Pixels are stored as 0xAARRGGBB (alpha in the high byte).

The Makefile calls this script automatically via 'make assets'.
"""

import sys
import os

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow is required.  Run:  pip install Pillow")
    sys.exit(1)


def png_to_header(input_path: str, output_path: str,
                  target_w: int = 32, target_h: int = 32) -> None:
    img = Image.open(input_path).convert("RGBA")
    img = img.resize((target_w, target_h), Image.LANCZOS)

    basename = os.path.basename(input_path)
    varname  = os.path.splitext(basename)[0] + "_img"        # e.g. pointer_img
    guard    = "ASSET_" + varname.upper() + "_H"             # e.g. ASSET_POINTER_IMG_H

    pixels = [img.getpixel((x, y)) for y in range(target_h) for x in range(target_w)]

    with open(output_path, "w") as f:
        f.write("/* Auto-generated by tools/png_to_header.py — DO NOT EDIT */\n")
        f.write(f"#ifndef {guard}\n")
        f.write(f"#define {guard}\n\n")
        # Compute the relative path from the output file back to src/types.h.
        # Convention: types.h lives in src/, so we walk up from the output dir.
        out_dir   = os.path.dirname(os.path.abspath(output_path))
        src_dir   = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src'))
        rel_types = os.path.relpath(os.path.join(src_dir, 'types.h'), out_dir)
        # Normalise to forward slashes (C preprocessor is fine with them)
        rel_types = rel_types.replace(os.sep, '/')
        f.write(f'#include "{rel_types}"\n\n')
        f.write(f"#define {varname.upper()}_W {target_w}u\n")
        f.write(f"#define {varname.upper()}_H {target_h}u\n\n")
        f.write("/* Pixels stored as 0xAARRGGBB */\n")
        f.write(f"static const uint32_t {varname}_pixels"
                f"[{target_w * target_h}] = {{\n")

        for i, (r, g, b, a) in enumerate(pixels):
            argb = (a << 24) | (r << 16) | (g << 8) | b
            if (i % target_w) == 0:
                f.write("    ")
            f.write(f"0x{argb:08X}")
            if i < len(pixels) - 1:
                f.write(", ")
            if (i + 1) % target_w == 0:
                f.write("\n")

        f.write("};\n\n")
        f.write(f"#endif /* {guard} */\n")

    print(f"[assets] Generated {output_path}  ({target_w}x{target_h})")


if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)

    w = int(sys.argv[3]) if len(sys.argv) > 3 else 32
    h = int(sys.argv[4]) if len(sys.argv) > 4 else 32
    png_to_header(sys.argv[1], sys.argv[2], w, h)